name: Mark stale pull requests

on:
  schedule:
  - cron: '29 22 * * 1-5'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "This PR hasn't seen activity in a week! Should it be merged, closed, or worked on further? If you want to keep it open, post a comment or remove the `stale` label – otherwise this will be closed in another week."
        close-pr-message: 'This PR was closed due to 2 weeks of inactivity. Feel free to reopen it if still relevant.'
        stale-issue-message: "This issue hasn't seen activity in a month! Should it be closed or worked on further? If you want to keep it open, post a comment or remove the `stale` label – otherwise this will be closed in two weeks."
        close-issue-message: 'This issue was closed due to 1,5 months of inactivity. Feel free to reopen it if still relevant.'
        stale-pr-label: 'stale'
        stale-issue-label: 'stale'
        days-before-pr-stale: 7
        days-before-pr-close: 7
        days-before-issue-stale: 30
        days-before-issue-close: 14
